# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Video.create(title: "Switched at Birth", description: "Switched at Birth is an American teen,family drama television series that premiered on ABC Family on June 6, 2011, at 9:00 ET/PT.The one-hour scripted drama is set in the Kansas City metropolitan area, and revolves around two teenagers who were switched at birth and grew up in very different environments: one in the old money suburb of Mission Hills, Kansas, and the other in working-class East Riverside, Missouri. According to ABC Family, it is the first mainstream television series to have multiple deaf and hard-of-hearing series regulars and scenes shot entirely in American Sign Language (ASL)", small_cover_url: "/tmp/switched_at_birth.jpg", large_cover_url: "/tmp/switched_at_birth_large.jpg", category_id: "4")
Video.create(title: "The Walking Dead", description: "The Walking Dead is an American post-apocalyptic horror drama television series developed by Frank Darabont. It is based on the comic book series of the same name by Robert Kirkman, Tony Moore, and Charlie Adlard. The series stars Andrew Lincoln as sheriff's deputy Rick Grimes,[3] who awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.", small_cover_url: "/tmp/walking_dead.jpg", large_cover_url: "/tmp/walking_dead_large.jpg",category_id: "1")
Video.create(title: "Monk", description: "Monk is an American comedy-drama detective mystery television series created by Andy Breckman and starring Tony Shalhoub as the eponymous character, Adrian Monk. It originally ran from 2002 to 2009 and is primarily a police procedural series, and also exhibits comic and dramatic tones in its exploration of the main characters' personal lives.", small_cover_url: "/tmp/monk.jpg", large_cover_url: "/tmp/monk_large.jpg",category_id: "1")
Video.create(title: "Bones", description: "BONES, a darkly amusing procedural entering its 10th season, is inspired by real-life forensic anthropologist and novelist Kathy Reichs. ", small_cover_url: "/tmp/bones.jpg", large_cover_url: "/tmp/bones_large.jpg",category_id: "1")
Video.create(title: "Futurama", description: "Fry, a pizza guy is accidentally frozen in 1999 and thawed out New Year's Eve 2999.", small_cover_url: "/tmp/futurama.jpg", large_cover_url: "/tmp/futurama_large.jpg",category_id: "2")
Video.create(title: "South Park", description: "Follows the misadventures of four irreverent grade-schoolers in the quiet, dysfunctional town of South Park, Colorado.", small_cover_url: "/tmp/south_park.jpg", large_cover_url: "/tmp/south_park_large.jpg",category_id: "5")
Video.create(title: "Gossip Girl", description: "Privileged teens living on the Upper Eastside of New York City.", small_cover_url: "/tmp/gossip_girls.jpg", large_cover_url: "/tmp/gossip_girls_large.jpg",category_id: "4")
Video.create(title: "The Magic School Bus ", description: "An eccentric schoolteacher takes her class on wondrous educational field trips with the help of a magical school bus.", small_cover_url: "/tmp/magic_school_bus.jpg", large_cover_url: "/tmp/magic_school_bus_large.jpg",category_id: "3")
Video.create(title: "House M.D.", description: "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.", small_cover_url: "/tmp/house.jpg", large_cover_url: "/tmp/house_large.jpg",category_id: "4")
Video.create(title: "Dexter", description: "A Miami police forensics expert moonlights as a serial killer of criminals whom he believes have escaped justice", small_cover_url: "/tmp/dexter.jpg", large_cover_url: "/tmp/dexter_large.jpg",category_id: "1")
Video.create(title: "Charmed", description: "Three sisters discover their destiny - to battle against the forces of evil, using their witchcraft. They are the Charmed Ones.", small_cover_url: "/tmp/charmed.jpg", large_cover_url: "/tmp/charmed_large.jpg",category_id: "1")
Video.create(title: "Workaholics", description: "A single-camera comedy featuring three friends who work together as telemarketers from 9 to 5 and live together from 5 to 9.", small_cover_url: "/tmp/workaholics.jpg", large_cover_url: "/tmp/workaholics_large.jpg",category_id: "1")
Video.create(title: "Sherlock ", description: "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.", small_cover_url: "/tmp/sherlock.jpg", large_cover_url: "/tmp/sherlock_large.jpg",category_id: "1")
Video.create(title: "The Big Bang Theory", description: "A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.", small_cover_url: "/tmp/TheBigBangTheory.png", large_cover_url: "/tmp/TheBigBangTheory_large.jpg",category_id: "1")
Video.create(title: "New Girl", description: "After a bad break-up, Jess, an offbeat young woman, moves into an apartment loft with three single men. Although they find her behavior very unusual, the men support her - most of the time.", small_cover_url: "/tmp/new_girl.jpg", large_cover_url: "/tmp/new_girl_large.jpg",category_id: "1")
Video.create(title: "Princess Mononoke", description: "On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.", small_cover_url: "/tmp/mononoke.jpg", large_cover_url: "/tmp/mononoke_large.jpg",category_id: "2")
Video.create(title: "Clannad", description: "A high school student who cares little about school or others meets a lonely girl who had to repeat a year while all her friends finished high school. He decides to hang out with her and soon meets more friendly students.", small_cover_url: "/tmp/clannad.png", large_cover_url: "/tmp/clannad_large.jpg",category_id: "2")
Video.create(title: "Clannad After Story", description: "A sequel to the recently wrapped anime based on the Key Clannad franchise. After Story is a path that opens in the original visual novel after all the other paths have been opened. Life continues on for Tomoya. A few months have passed since he confessed his love to Nagisa. Now entering the second semester, he continues to meet a variety of different people, expanding his own world in the process. As well, Tomoya and Nagisa's relationship begins to enter a level of intimacy unlike before. Through his relationship with Nagisa, and his various encounters, Tomoya begins to understand the meaning and importance of family. Unfortunately, as Tomoya and Nagisa begin their own family together, they are faced with many hardships and challenges along the way. The sequel to the first anime, Clannad. After confessing his love for Nagisa Furukawa, life for Tomoya goes on. As he continues to meet and help more people with their own family problems, Tomoya's relationship with Nagisa grows to a greater level than ever before. Through his various encounters and the start of his new family with Nagisa, Tomoya will finally begin to understand the value of the most precious thing that we have in this world; the value of having a family.", small_cover_url: "/tmp/clannad_as.jpg", large_cover_url: "/tmp/clannad_as_large.jpg",category_id: "2")
Video.create(title: "Clifford the Big Red Dog", description: "The adventures of a larger-than-life red dog on Bridwell Island.", small_cover_url: "/tmp/clifford.jpg", large_cover_url: "/tmp/clifford_large.jpg",category_id: "3")
Video.create(title: "How to Train Your Dragon", description: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.", small_cover_url: "/tmp/dragon.jpg", large_cover_url: "/tmp/dragon_large.jpg",category_id: "3")
Video.create(title: "Monsters, Inc.", description: "Monsters generate their city's power by scaring children, but they are terribly afraid themselves of being contaminated by children, so when one enters Monstropolis, top scarer Sulley finds his world disrupted.", small_cover_url: "/tmp/monster.jpg", large_cover_url: "/tmp/monster_large.jpg",category_id: "3")
Video.create(title: "Being Erica", description: "Therapist Dr. Tom - who is constantly spouting famous and not so famous historical quotes - is Erica Strange's savior and worst enemy. Erica, a young adult woman, is having a bad life because of the bad decisions she's made. Erica provides Dr. Tom with a long list of those pivotal moments in her life that she feels have led to the bad state she is in today. Erica is initially unaware of what Dr. Tom is intending on doing with this list. What he does do is transport her back in time to each of those moments so that she, with all the knowledge of her present day life, can make better decisions to fix her life. Regardless of these new decisions, Dr. Tom hopes that Erica will come to the realization that although the opinions of oth", small_cover_url: "/tmp/being_erica.jpg", large_cover_url: "/tmp/being_erica_large.jpg",category_id: "5")
Video.create(title: "Drop Dead Diva", description: "A vapid aspiring model killed in a car crash gets brought back to life as an intelligent, overweight lawyer, hoping to find the meaning of inner beauty.", small_cover_url: "/tmp/drop_dead_diva.jpg", large_cover_url: "/tmp/drop_dead_diva_large.jpg",category_id: "5")
Video.create(title: "Bomb Girls", description: "A drama about World War II women at work in a munitions factory.", small_cover_url: "/tmp/bomb_girls.jpg", large_cover_url: "/tmp/bomb_girls_large.jpg",category_id: "4")
Video.create(title: "How I Met Your Mother ", description: "Ted searches for the woman of his dreams in New York City with the help of his four best friends.", small_cover_url: "/tmp/howimetyourmother.jpg", large_cover_url: "/tmp/howimetyourmother_large.jpg",category_id: "5")
Video.create(title: "Saved by the Bell ", description: "A TV show centered on six students and their years at Bayside High School in Palisades, California.", small_cover_url: "/tmp/Saved_by_the_Bell.png", large_cover_url: "/tmp/Saved_by_the_Bell_large.jpg",category_id: "5")


Category.create(name: "TV Shows")
Category.create(name: "Anime")
Category.create(name: "Children & Family")
Category.create(name: "Dramas")
Category.create(name: "Comedies")



